/**
 * src/services/vaultMarketReport.ts
 * VAULT Market Report Service — V3-27
 *
 * Generates and retrieves weekly material market reports.
 * Reports are auto-generated by SCOUT every Monday and stored in Supabase.
 * In V3 external, reports are mocked. On V2 integration, replace
 * `_mockReportCache` with Supabase reads/writes.
 *
 * Public API:
 *   getLatestMarketReport()         → Promise<MarketReport | null>
 *   generateWeeklyMarketReport()    → Promise<MarketReport>
 *   hasNewReport()                  → boolean
 *   markReportSeen()                → void
 *
 * Supabase table required (V2 integration):
 *   `material_market_reports` — id, week_label, generated_at, report_data (JSONB),
 *                               is_seen (boolean), user_id
 */

import { syncToSupabase, fetchFromSupabase } from './supabaseService';

// ─── Types ─────────────────────────────────────────────────────────────────────

export interface MarketReportItem {
  item_name: string;
  display_name: string;
  vault_price: number;
  market_best: number;
  market_best_supplier: string;
  unit: string;
  diff_pct: number;           // positive = vault above market, negative = vault below
  direction: 'up' | 'down' | 'stable'; // price trend since last week
  weekly_change_pct: number;  // market price change vs prior week
  potential_savings_per_unit: number;
  status: 'green' | 'yellow' | 'red'; // competitiveness status
  recommendation: string;
}

export interface MarketReportTopMover {
  item_name: string;
  display_name: string;
  supplier_name: string;
  change_pct: number;
  direction: 'up' | 'down';
  current_price: number;
  previous_price: number;
  unit: string;
  severity: 'info' | 'warning' | 'critical';
}

export interface MarketReport {
  id: string;
  week_label: string;           // e.g. "Mar 30 – Apr 5, 2026"
  generated_at: string;         // ISO timestamp (Monday ~6:00 AM)
  items_tracked: number;
  avg_savings_pct: number;      // avg % VAULT is above market across all items
  total_potential_savings: number; // total $ if all items moved to market best
  items_at_risk: number;        // items where vault_price > 25% above market
  items_competitive: number;    // items where vault_price ≤ 10% of market
  top_movers: MarketReportTopMover[];
  savings_opportunities: MarketReportItem[];
  summary: string;
  is_new: boolean;              // true until user views report
}

// ─── Mock Report Data ──────────────────────────────────────────────────────────

const MOCK_TOP_MOVERS: MarketReportTopMover[] = [
  {
    item_name: 'thhn wire 12 awg black',
    display_name: '12 AWG THHN Black',
    supplier_name: 'Rexel',
    change_pct: -4.2,
    direction: 'down',
    current_price: 84.99,
    previous_price: 88.73,
    unit: 'per 1000ft spool',
    severity: 'info',
  },
  {
    item_name: 'square d 200a 40-circuit panel',
    display_name: 'Square D 200A 40-Ckt Panel',
    supplier_name: 'Local Supplier',
    change_pct: 8.7,
    direction: 'up',
    current_price: 345.00,
    previous_price: 317.39,
    unit: 'each',
    severity: 'warning',
  },
  {
    item_name: '3/4 emt conduit 10ft',
    display_name: '3/4" EMT Conduit 10ft',
    supplier_name: 'Graybar',
    change_pct: -2.1,
    direction: 'down',
    current_price: 8.40,
    previous_price: 8.58,
    unit: 'per stick (10ft)',
    severity: 'info',
  },
  {
    item_name: 'leviton 20a decora gfci',
    display_name: 'Leviton 20A Decora GFCI',
    supplier_name: 'Rexel',
    change_pct: 11.3,
    direction: 'up',
    current_price: 19.99,
    previous_price: 17.96,
    unit: 'each',
    severity: 'critical',
  },
  {
    item_name: 'eaton 20a single pole breaker',
    display_name: 'Eaton 20A SP Breaker',
    supplier_name: 'Local Supplier',
    change_pct: -6.8,
    direction: 'down',
    current_price: 9.95,
    previous_price: 10.68,
    unit: 'each',
    severity: 'info',
  },
];

const MOCK_SAVINGS_OPPORTUNITIES: MarketReportItem[] = [
  {
    item_name: '3/4 emt conduit 10ft',
    display_name: '3/4" EMT Conduit 10ft',
    vault_price: 11.50,
    market_best: 7.75,
    market_best_supplier: 'Local Supplier',
    unit: 'per stick (10ft)',
    diff_pct: 48.4,
    direction: 'down',
    weekly_change_pct: -2.1,
    potential_savings_per_unit: 3.75,
    status: 'red',
    recommendation: 'Update to Local Supplier — save $3.75/stick. Stock available.',
  },
  {
    item_name: 'leviton 20a decora gfci',
    display_name: 'Leviton 20A Decora GFCI',
    vault_price: 28.00,
    market_best: 18.75,
    market_best_supplier: 'Local Supplier',
    unit: 'each',
    diff_pct: 49.3,
    direction: 'up',
    weekly_change_pct: 11.3,
    potential_savings_per_unit: 9.25,
    status: 'red',
    recommendation: 'Update to Local Supplier — save $9.25/unit. Consider Rexel at $19.99 as backup.',
  },
  {
    item_name: 'square d 20a single pole breaker',
    display_name: 'Square D 20A SP Breaker',
    vault_price: 12.50,
    market_best: 10.50,
    market_best_supplier: 'Local Supplier',
    unit: 'each',
    diff_pct: 19.0,
    direction: 'stable',
    weekly_change_pct: 0.5,
    potential_savings_per_unit: 2.00,
    status: 'yellow',
    recommendation: 'Local Supplier saves $2.00/unit on 5+ pack orders.',
  },
  {
    item_name: 'leviton 20a tamper resistant receptacle',
    display_name: 'Leviton 20A TR Receptacle',
    vault_price: 5.50,
    market_best: 4.75,
    market_best_supplier: 'Local Supplier',
    unit: 'each',
    diff_pct: 15.8,
    direction: 'stable',
    weekly_change_pct: -0.4,
    potential_savings_per_unit: 0.75,
    status: 'yellow',
    recommendation: 'Local Supplier competitive at $4.75 for 25+ unit orders.',
  },
  {
    item_name: 'thhn wire 12 awg black',
    display_name: '12 AWG THHN Black',
    vault_price: 89.50,
    market_best: 82.00,
    market_best_supplier: 'Local Supplier',
    unit: 'per 1000ft spool',
    diff_pct: 9.1,
    direction: 'down',
    weekly_change_pct: -4.2,
    potential_savings_per_unit: 7.50,
    status: 'green',
    recommendation: 'VAULT price is competitive. Rexel at $84.99 is solid alternative.',
  },
  {
    item_name: 'thhn wire 10 awg black',
    display_name: '10 AWG THHN Black',
    vault_price: 94.00,
    market_best: 88.00,
    market_best_supplier: 'Local Supplier',
    unit: 'per 500ft spool',
    diff_pct: 6.8,
    direction: 'stable',
    weekly_change_pct: 1.2,
    potential_savings_per_unit: 6.00,
    status: 'green',
    recommendation: 'VAULT price is competitive. Local Supplier in stock.',
  },
];

// ─── In-Memory Report Cache ────────────────────────────────────────────────────

/** Simulates the Supabase `material_market_reports` table in V3 external. */
const _mockReport: MarketReport = {
  id: 'report-2026-w14',
  week_label: 'Mar 30 – Apr 5, 2026',
  generated_at: '2026-03-30T06:00:00.000Z',
  items_tracked: 21,
  avg_savings_pct: 14.2,
  total_potential_savings: 847.50,
  items_at_risk: 2,
  items_competitive: 8,
  top_movers: MOCK_TOP_MOVERS,
  savings_opportunities: MOCK_SAVINGS_OPPORTUNITIES,
  summary:
    'Market conditions mixed this week. GFCI and panel pricing moved up significantly — ' +
    'review your VAULT prices for those categories. Wire pricing continues to soften. ' +
    'Two line items are priced >25% above market best — flag for immediate review.',
  is_new: true,
};

// Tracks whether the current user has seen the latest report
let _reportSeen = false;

// ─── Public API ────────────────────────────────────────────────────────────────

/**
 * Returns the latest market report.
 * V2 integration: replace with `fetchFromSupabase('material_market_reports', ...)`
 */
export async function getLatestMarketReport(): Promise<MarketReport | null> {
  // STUB — wire to Supabase on V2 integration
  // const rows = await fetchFromSupabase('material_market_reports', { order: 'generated_at.desc', limit: 1 });
  // return rows?.[0] ?? null;

  return { ..._mockReport, is_new: !_reportSeen };
}

/**
 * Auto-generates a fresh weekly market report.
 * Called every Monday by SCOUT. In production, this runs as a Supabase
 * scheduled function or n8n workflow. In V3 external, returns mock data.
 *
 * V2 integration: replace body with real Supabase write +
 * SCOUT agent scan across all tracked items.
 */
export async function generateWeeklyMarketReport(): Promise<MarketReport> {
  const now = new Date().toISOString();

  // STUB — production would: scan all SCOUT-tracked items, compare vs VAULT prices,
  // compute top movers, persist to Supabase, then trigger notification.
  await syncToSupabase({
    table: 'material_market_reports',
    data: {
      id: _mockReport.id,
      week_label: _mockReport.week_label,
      generated_at: now,
      report_data: _mockReport,
      is_seen: false,
    },
    operation: 'upsert',
  });

  _reportSeen = false;
  return { ..._mockReport, generated_at: now, is_new: true };
}

/**
 * Returns true if a new (unseen) market report is available.
 * Used to show the notification badge on the sidebar.
 */
export function hasNewReport(): boolean {
  return !_reportSeen;
}

/**
 * Marks the current report as seen.
 * Call when the user navigates to Material Intelligence or opens the report.
 * V2 integration: `syncToSupabase('material_market_reports', { is_seen: true })`
 */
export function markReportSeen(): void {
  _reportSeen = true;
}
