/**
 * App Brain Backlog Registry - Type Definitions
 * 
 * Defines the schema for task tracking, domain organization, and backlog management.
 * This is the foundation for the Backlog Registry that powers the App Brain control tower.
 */

/**
 * Task priority levels
 */
export type TaskPriority = 'critical' | 'high' | 'medium' | 'low' | 'backlog';

/**
 * Task execution status
 */
export type TaskStatus = 
  | 'backlog' 
  | 'planned' 
  | 'in-progress' 
  | 'blocked' 
  | 'review' 
  | 'completed' 
  | 'archived';

/**
 * Risk assessment levels
 */
export type RiskLevel = 'critical' | 'high' | 'medium' | 'low' | 'none';

/**
 * Domain classification for task organization
 */
export type TaskDomain = 
  | 'core-shell'
  | 'home'
  | 'projects'
  | 'project-inner'
  | 'estimate'
  | 'material-takeoff'
  | 'field-logs'
  | 'graph-dashboard'
  | 'money'
  | 'settings'
  | 'blueprint-pdf'
  | 'price-book'
  | 'leads-sales'
  | 'ai-nexus'
  | 'admin-app-brain'
  | 'sync-persistence'
  | 'integrations';

/**
 * Individual backlog task record
 */
export interface BacklogTask {
  /**
   * Unique task identifier (e.g., "appbrain-w01-a5-001")
   */
  taskId: string;

  /**
   * Domain this task belongs to
   */
  domain: TaskDomain;

  /**
   * Feature/module name (e.g., "Backlog Registry Schema", "Neural World View")
   */
  feature: string;

  /**
   * Short human-readable title
   */
  title: string;

  /**
   * Detailed description of what needs to be done
   */
  description?: string;

  /**
   * Current execution status
   */
  status: TaskStatus;

  /**
   * Priority ranking for execution order
   */
  priority: TaskPriority;

  /**
   * Risk assessment for this task
   */
  risk: RiskLevel;

  /**
   * AI Agent assigned to execute this task (e.g., "appbrain-haiku-a5")
   */
  assignedAgent?: string;

  /**
   * Related files that should be modified or created
   */
  relatedFiles: string[];

  /**
   * Task IDs that block this task or that this task blocks
   */
  dependencies?: string[];

  /**
   * Quality assurance checklist items
   */
  qaChecklist?: string[];

  /**
   * Implementation notes, design decisions, gotchas
   */
  notes?: string;

  /**
   * Where this task originated from (e.g., "Christian-backlog", "audit-finding", "wave-session")
   */
  source: string;

  /**
   * ISO 8601 timestamp when task was created
   */
  createdAt: string;

  /**
   * ISO 8601 timestamp when task was last updated
   */
  updatedAt: string;
}

/**
 * Domain bucket - groups related tasks by domain
 */
export interface DomainBucket {
  /**
   * Domain identifier
   */
  domain: TaskDomain;

  /**
   * Display name for the domain
   */
  displayName: string;

  /**
   * Brief description of what this domain covers
   */
  description: string;

  /**
   * Array of tasks in this domain
   */
  tasks: BacklogTask[];

  /**
   * Statistics about this domain
   */
  stats: {
    total: number;
    completed: number;
    inProgress: number;
    blocked: number;
    critical: number;
  };
}

/**
 * Full Backlog Registry structure
 */
export interface BacklogRegistry {
  /**
   * Metadata about the registry
   */
  metadata: {
    /**
     * Version of the schema
     */
    version: string;

    /**
     * Last update timestamp
     */
    lastUpdated: string;

    /**
     * Total count of all tasks across all domains
     */
    totalTasks: number;

    /**
     * Total completed tasks
     */
    completedTasks: number;

    /**
     * Manifest file reference for generated code (generated by generate-app-brain-manifest.mjs)
     */
    manifestReference?: string;
  };

  /**
   * All domain buckets, keyed by domain ID
   */
  domains: Record<TaskDomain, DomainBucket>;

  /**
   * Summary statistics
   */
  summary: {
    byStatus: Record<TaskStatus, number>;
    byPriority: Record<TaskPriority, number>;
    byRisk: Record<RiskLevel, number>;
    byAgent: Record<string, number>;
  };
}

/**
 * Helper type for creating a new task with defaults
 */
export interface CreateBacklogTaskInput {
  taskId: string;
  domain: TaskDomain;
  feature: string;
  title: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  risk?: RiskLevel;
  assignedAgent?: string;
  relatedFiles?: string[];
  dependencies?: string[];
  qaChecklist?: string[];
  notes?: string;
  source?: string;
}
