/*
 * GENERATED FILE - DO NOT HAND EDIT.
 * Run node scripts/generate-app-brain-work-manifest.mjs to refresh.
 * Generated by scripts/generate-app-brain-work-manifest.mjs.
 * generatedAt changes each time the generator is run.
 */
export const GENERATED_APP_BRAIN_WORK_MANIFEST = {
  "schemaVersion": "app-brain-work-manifest-v1",
  "generatedAt": "2026-06-07T07:43:52.768Z",
  "generatedBy": "scripts/generate-app-brain-work-manifest.mjs",
  "refreshCommand": "node scripts/generate-app-brain-work-manifest.mjs",
  "snapshotWarning": "Generated snapshot · not watch mode. Re-run the generator to refresh; no automatic live tracking or git hooks.",
  "sourcesRead": [
    "solarupgrade_agent_context/APP_BRAIN_ACTIVE_SESSIONS.json",
    "solarupgrade_agent_context/APP_BRAIN_AGENT_RULES.json",
    "solarupgrade_agent_context/APP_BRAIN_GLOBAL_RULES.json",
    "solarupgrade_agent_context/APP_BRAIN_SKILLS.json",
    "solarupgrade_agent_context/APP_BRAIN_TASK_REGISTRY.json",
    "solarupgrade_agent_context/SOLARUPGRADE_CLAUDE.md",
    "solarupgrade_agent_context/SOLARUPGRADE_CODEX.md",
    "solarupgrade_agent_context/SOLARUPGRADE_CURSOR.md",
    "solarupgrade_agent_context/SOLARUPGRADE_SHARED_CONTEXT.md"
  ],
  "sourcesMissing": [
    "solarupgrade_agent_context/SOLARUPGRADE_HAIKU.md"
  ],
  "activeSessionCount": 5,
  "overallHealthy": true,
  "typeCheckPassRate": 100,
  "agentsSummary": [
    {
      "agent": "Claude",
      "sessionCount": 1,
      "activeCount": 0,
      "pendingCount": 1,
      "primaryTask": "Neural World View implementation",
      "status": "pending",
      "domain": "neural-world",
      "contextHealth": [
        "context-recent"
      ],
      "domains": [
        "neural-world"
      ]
    },
    {
      "agent": "Codex",
      "sessionCount": 1,
      "activeCount": 0,
      "pendingCount": 1,
      "primaryTask": "Visual Suite chart system enhancement",
      "status": "pending",
      "domain": "visual-suite",
      "contextHealth": [
        "context-recent"
      ],
      "domains": [
        "visual-suite"
      ]
    },
    {
      "agent": "Cursor",
      "sessionCount": 1,
      "activeCount": 0,
      "pendingCount": 1,
      "primaryTask": "ORB LAB initialization",
      "status": "pending",
      "domain": "orb-lab",
      "contextHealth": [
        "context-recent"
      ],
      "domains": [
        "orb-lab"
      ]
    },
    {
      "agent": "Haiku",
      "sessionCount": 1,
      "activeCount": 1,
      "pendingCount": 0,
      "primaryTask": "Live Work Control Tower schema seed foundation",
      "status": "active",
      "domain": "app-brain-core",
      "contextHealth": [
        "context-missing"
      ],
      "domains": [
        "app-brain-core"
      ]
    },
    {
      "agent": "Manual/Owner",
      "sessionCount": 1,
      "activeCount": 0,
      "pendingCount": 1,
      "primaryTask": "App Brain Wave 01 oversight and integration planning",
      "status": "pending",
      "domain": "app-brain-core",
      "contextHealth": [
        "context-recent"
      ],
      "domains": [
        "app-brain-core"
      ]
    }
  ],
  "registrySummary": {
    "sessionsCount": 5,
    "globalRulesCount": 10,
    "agentRulesCount": 5,
    "skillsCount": 0,
    "backlogDomainsCount": 17,
    "backlogTasksCount": 0
  },
  "contextFiles": [
    {
      "key": "shared",
      "label": "Shared context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_SHARED_CONTEXT.md",
      "exists": true,
      "sizeBytes": 242457,
      "modifiedAt": "2026-06-07T07:41:03.686Z",
      "freshness": "recent",
      "lastReportExcerpt": "COMPACT HANDOFF FOR NEXT CHAT: Home repair pass complete on `main`. Pipeline subtitle uses active-project count; agenda linking uses a real project picker modal; agenda cards scroll after 10 task rows. Scope limited t..."
    },
    {
      "key": "claude",
      "label": "Claude context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_CLAUDE.md",
      "exists": true,
      "sizeBytes": 151439,
      "modifiedAt": "2026-06-07T06:58:17.331Z",
      "freshness": "recent",
      "lastReportExcerpt": "Compact handoff for next agent/chat: Inner Project Batch 3 complete on `main`. Progress tab phase headers now show total hours per phase (e.g. \"3 tasks · 12h\"). Estimate labor phase headers now show a hours pill (e.g...."
    },
    {
      "key": "codex",
      "label": "Codex context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_CODEX.md",
      "exists": true,
      "sizeBytes": 102455,
      "modifiedAt": "2026-06-07T03:37:25.359Z",
      "freshness": "recent",
      "lastReportExcerpt": "Compact handoff for next agent/chat: Home alerts polish complete on `main`. `V15rHome.tsx` now filters AI alerts to active projects, persists generated-alert deletes, filters archived linked custom alerts, uses active..."
    },
    {
      "key": "cursor",
      "label": "Cursor context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_CURSOR.md",
      "exists": true,
      "sizeBytes": 43144,
      "modifiedAt": "2026-06-07T07:41:06.469Z",
      "freshness": "recent",
      "lastReportExcerpt": "Compact handoff: Opt-in CLI refresh/watch utility live. Panel shows generated snapshot only — not live websocket state. No hooks, auto-commit, secrets, or financial values."
    },
    {
      "key": "haiku",
      "label": "Haiku context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_HAIKU.md",
      "exists": false,
      "sizeBytes": 0,
      "modifiedAt": null,
      "freshness": "missing",
      "lastReportExcerpt": null
    }
  ],
  "gitStatus": {
    "available": true,
    "branch": "main",
    "clean": false,
    "changedFileCount": 10,
    "warning": null
  }
} as const
