/*
 * GENERATED FILE - DO NOT HAND EDIT.
 * Run node scripts/generate-app-brain-work-manifest.mjs to refresh.
 * Generated by scripts/generate-app-brain-work-manifest.mjs.
 * generatedAt changes each time the generator is run.
 */
export const GENERATED_APP_BRAIN_WORK_MANIFEST = {
  "schemaVersion": "app-brain-work-manifest-v1",
  "generatedAt": "2026-06-09T06:58:47.710Z",
  "generatedBy": "scripts/generate-app-brain-work-manifest.mjs",
  "refreshCommand": "node scripts/generate-app-brain-work-manifest.mjs",
  "snapshotWarning": "Generated snapshot · not watch mode. Re-run the generator to refresh; no automatic live tracking or git hooks.",
  "sourcesRead": [
    "solarupgrade_agent_context/APP_BRAIN_ACTIVE_SESSIONS.json",
    "solarupgrade_agent_context/APP_BRAIN_AGENT_RULES.json",
    "solarupgrade_agent_context/APP_BRAIN_GLOBAL_RULES.json",
    "solarupgrade_agent_context/APP_BRAIN_SKILLS.json",
    "solarupgrade_agent_context/APP_BRAIN_TASK_REGISTRY.json",
    "solarupgrade_agent_context/SOLARUPGRADE_CLAUDE.md",
    "solarupgrade_agent_context/SOLARUPGRADE_CODEX.md",
    "solarupgrade_agent_context/SOLARUPGRADE_CURSOR.md",
    "solarupgrade_agent_context/SOLARUPGRADE_SHARED_CONTEXT.md"
  ],
  "sourcesMissing": [
    "solarupgrade_agent_context/SOLARUPGRADE_HAIKU.md"
  ],
  "activeSessionCount": 5,
  "overallHealthy": true,
  "typeCheckPassRate": 100,
  "agentsSummary": [
    {
      "agent": "Claude",
      "sessionCount": 1,
      "activeCount": 0,
      "pendingCount": 1,
      "primaryTask": "Neural World View implementation",
      "status": "pending",
      "domain": "neural-world",
      "contextHealth": [
        "context-recent"
      ],
      "domains": [
        "neural-world"
      ]
    },
    {
      "agent": "Codex",
      "sessionCount": 1,
      "activeCount": 0,
      "pendingCount": 1,
      "primaryTask": "Visual Suite chart system enhancement",
      "status": "pending",
      "domain": "visual-suite",
      "contextHealth": [
        "context-recent"
      ],
      "domains": [
        "visual-suite"
      ]
    },
    {
      "agent": "Cursor",
      "sessionCount": 1,
      "activeCount": 0,
      "pendingCount": 1,
      "primaryTask": "ORB LAB initialization",
      "status": "pending",
      "domain": "orb-lab",
      "contextHealth": [
        "context-recent"
      ],
      "domains": [
        "orb-lab"
      ]
    },
    {
      "agent": "Haiku",
      "sessionCount": 1,
      "activeCount": 1,
      "pendingCount": 0,
      "primaryTask": "Live Work Control Tower schema seed foundation",
      "status": "active",
      "domain": "app-brain-core",
      "contextHealth": [
        "context-missing"
      ],
      "domains": [
        "app-brain-core"
      ]
    },
    {
      "agent": "Manual/Owner",
      "sessionCount": 1,
      "activeCount": 0,
      "pendingCount": 1,
      "primaryTask": "App Brain Wave 01 oversight and integration planning",
      "status": "pending",
      "domain": "app-brain-core",
      "contextHealth": [
        "context-recent"
      ],
      "domains": [
        "app-brain-core"
      ]
    }
  ],
  "registrySummary": {
    "sessionsCount": 5,
    "globalRulesCount": 10,
    "agentRulesCount": 5,
    "skillsCount": 0,
    "backlogDomainsCount": 17,
    "backlogTasksCount": 0
  },
  "contextFiles": [
    {
      "key": "shared",
      "label": "Shared context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_SHARED_CONTEXT.md",
      "exists": true,
      "sizeBytes": 293956,
      "modifiedAt": "2026-06-09T06:58:44.648Z",
      "freshness": "recent",
      "lastReportExcerpt": "COMPACT HANDOFF FOR NEXT CHAT: Header fix pass complete on `main`. `V15rLayout.tsx` now has one guarded Save button wired to `forceSyncToCloud()`, red SVC Unbilled, corrected Exposure value, and a project-only Coming ..."
    },
    {
      "key": "claude",
      "label": "Claude context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_CLAUDE.md",
      "exists": true,
      "sizeBytes": 256583,
      "modifiedAt": "2026-06-09T06:58:45.771Z",
      "freshness": "recent",
      "lastReportExcerpt": "COMPACT HANDOFF FOR NEXT CHAT: Labor Allocation modal in V15rEstimateTab.tsx now has a full-width SUGGESTED HOURLY RATE box at ~line 3508 (after top-4 summary grid, before Task Cost Summary). Value = `blendedEmployeeB..."
    },
    {
      "key": "codex",
      "label": "Codex context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_CODEX.md",
      "exists": true,
      "sizeBytes": 107443,
      "modifiedAt": "2026-06-08T17:14:14.216Z",
      "freshness": "recent",
      "lastReportExcerpt": "Compact handoff for next agent/chat: Home tablet fix pass complete on `main` (`5c571aa`). Removed Home `min-h-screen`; shell main now uses `maxWidth: 100%` + `overscrollBehavior: contain`. Safe-area dedupe and calenda..."
    },
    {
      "key": "cursor",
      "label": "Cursor context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_CURSOR.md",
      "exists": true,
      "sizeBytes": 63541,
      "modifiedAt": "2026-06-08T17:26:40.144Z",
      "freshness": "recent",
      "lastReportExcerpt": "Compact handoff for next agent/chat: iPad Safari regression after `bcaa72d` is primarily **horizontal flex containment + safe-area stacking**, not the `min-h-screen` removal itself. Keep `maxWidth:100%`; add `min-w-0`..."
    },
    {
      "key": "haiku",
      "label": "Haiku context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_HAIKU.md",
      "exists": false,
      "sizeBytes": 0,
      "modifiedAt": null,
      "freshness": "missing",
      "lastReportExcerpt": null
    }
  ],
  "gitStatus": {
    "available": true,
    "branch": "main",
    "clean": false,
    "changedFileCount": 8,
    "warning": null
  }
} as const
