/*
 * GENERATED FILE - DO NOT HAND EDIT.
 * Run node scripts/generate-app-brain-work-manifest.mjs to refresh.
 * Generated by scripts/generate-app-brain-work-manifest.mjs.
 * generatedAt changes each time the generator is run.
 */
export const GENERATED_APP_BRAIN_WORK_MANIFEST = {
  "schemaVersion": "app-brain-work-manifest-v1",
  "generatedAt": "2026-06-07T03:48:26.447Z",
  "generatedBy": "scripts/generate-app-brain-work-manifest.mjs",
  "refreshCommand": "node scripts/generate-app-brain-work-manifest.mjs",
  "snapshotWarning": "Generated snapshot · not watch mode. Re-run the generator to refresh; no automatic live tracking or git hooks.",
  "sourcesRead": [
    "solarupgrade_agent_context/APP_BRAIN_ACTIVE_SESSIONS.json",
    "solarupgrade_agent_context/APP_BRAIN_AGENT_RULES.json",
    "solarupgrade_agent_context/APP_BRAIN_GLOBAL_RULES.json",
    "solarupgrade_agent_context/APP_BRAIN_SKILLS.json",
    "solarupgrade_agent_context/APP_BRAIN_TASK_REGISTRY.json",
    "solarupgrade_agent_context/SOLARUPGRADE_CLAUDE.md",
    "solarupgrade_agent_context/SOLARUPGRADE_CODEX.md",
    "solarupgrade_agent_context/SOLARUPGRADE_CURSOR.md",
    "solarupgrade_agent_context/SOLARUPGRADE_SHARED_CONTEXT.md"
  ],
  "sourcesMissing": [
    "solarupgrade_agent_context/SOLARUPGRADE_HAIKU.md"
  ],
  "activeSessionCount": 5,
  "overallHealthy": true,
  "typeCheckPassRate": 100,
  "agentsSummary": [
    {
      "agent": "Claude",
      "sessionCount": 1,
      "activeCount": 0,
      "pendingCount": 1,
      "primaryTask": "Neural World View implementation",
      "status": "pending",
      "domain": "neural-world",
      "contextHealth": [
        "context-recent"
      ],
      "domains": [
        "neural-world"
      ]
    },
    {
      "agent": "Codex",
      "sessionCount": 1,
      "activeCount": 0,
      "pendingCount": 1,
      "primaryTask": "Visual Suite chart system enhancement",
      "status": "pending",
      "domain": "visual-suite",
      "contextHealth": [
        "context-recent"
      ],
      "domains": [
        "visual-suite"
      ]
    },
    {
      "agent": "Cursor",
      "sessionCount": 1,
      "activeCount": 0,
      "pendingCount": 1,
      "primaryTask": "ORB LAB initialization",
      "status": "pending",
      "domain": "orb-lab",
      "contextHealth": [
        "context-recent"
      ],
      "domains": [
        "orb-lab"
      ]
    },
    {
      "agent": "Haiku",
      "sessionCount": 1,
      "activeCount": 1,
      "pendingCount": 0,
      "primaryTask": "Live Work Control Tower schema seed foundation",
      "status": "active",
      "domain": "app-brain-core",
      "contextHealth": [
        "context-missing"
      ],
      "domains": [
        "app-brain-core"
      ]
    },
    {
      "agent": "Manual/Owner",
      "sessionCount": 1,
      "activeCount": 0,
      "pendingCount": 1,
      "primaryTask": "App Brain Wave 01 oversight and integration planning",
      "status": "pending",
      "domain": "app-brain-core",
      "contextHealth": [
        "context-recent"
      ],
      "domains": [
        "app-brain-core"
      ]
    }
  ],
  "registrySummary": {
    "sessionsCount": 5,
    "globalRulesCount": 10,
    "agentRulesCount": 5,
    "skillsCount": 0,
    "backlogDomainsCount": 17,
    "backlogTasksCount": 0
  },
  "contextFiles": [
    {
      "key": "shared",
      "label": "Shared context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_SHARED_CONTEXT.md",
      "exists": true,
      "sizeBytes": 252598,
      "modifiedAt": "2026-06-07T03:47:53.447Z",
      "freshness": "recent",
      "lastReportExcerpt": "COMPACT HANDOFF FOR NEXT CHAT: App Brain Wave 2 is a read-only Directory Brain MVP. The regenerated directory manifest now has source-file metadata; the Directory panel filters/searches/selects files; the File Profile..."
    },
    {
      "key": "claude",
      "label": "Claude context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_CLAUDE.md",
      "exists": true,
      "sizeBytes": 121681,
      "modifiedAt": "2026-06-07T03:47:55.752Z",
      "freshness": "recent",
      "lastReportExcerpt": "Compact handoff for next agent/chat: Projects tab cards now match Home tab cards on main branch. Root cause: V15rProjectsPanel.tsx has its own inline renderProjectCard function (separate from shared ProjectCard.tsx us..."
    },
    {
      "key": "codex",
      "label": "Codex context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_CODEX.md",
      "exists": true,
      "sizeBytes": 102455,
      "modifiedAt": "2026-06-07T03:37:25.359Z",
      "freshness": "recent",
      "lastReportExcerpt": "Compact handoff for next agent/chat: Home alerts polish complete on `main`. `V15rHome.tsx` now filters AI alerts to active projects, persists generated-alert deletes, filters archived linked custom alerts, uses active..."
    },
    {
      "key": "cursor",
      "label": "Cursor context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_CURSOR.md",
      "exists": true,
      "sizeBytes": 34656,
      "modifiedAt": "2026-06-07T03:03:24.685Z",
      "freshness": "recent",
      "lastReportExcerpt": "Compact handoff: App Brain now hides operational finance KPIs in architecture mode and shows five read-only Control Tower panels from Wave 01 JSON seeds via `appBrainSeedData.ts`. 3D map, filters, inspector, and gener..."
    },
    {
      "key": "haiku",
      "label": "Haiku context",
      "path": "solarupgrade_agent_context/SOLARUPGRADE_HAIKU.md",
      "exists": false,
      "sizeBytes": 0,
      "modifiedAt": null,
      "freshness": "missing",
      "lastReportExcerpt": null
    }
  ],
  "gitStatus": {
    "available": true,
    "branch": "main",
    "clean": false,
    "changedFileCount": 7,
    "warning": null
  }
} as const
