import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(join(process.cwd(), path), 'utf8')
const panel = read('src/components/admin/AdminTaskDelegationPanel.tsx')
const board = read('src/components/admin/AdminWorkOrderAssignmentBoard.tsx')
const form = read('src/components/admin/AdminWorkOrderAssignmentForm.tsx')
const team = read('src/components/v15r/V15rTeamPanel.tsx')
const crew = read('src/views/CrewPortal.tsx')
const service = read('src/services/employeeTaskAssignmentService.ts')
const viewer = read('src/components/employee/EmployeeWorkOrderViewer.tsx')
const migration = read('supabase/migrations/098_admin_work_order_assignment_board.sql')
const migration096 = read('supabase/migrations/096_work_order_snapshot_delivery.sql')

describe('shared admin Work Order assignment integration', () => {
  it('keeps Team and Crew Portal on the same shared panel and one board/form implementation', () => {
    expect(team).toContain("import AdminTaskDelegationPanel from '@/components/admin/AdminTaskDelegationPanel'")
    expect(team).toContain('<AdminTaskDelegationPanel />')
    expect(crew).toContain("import AdminTaskDelegationPanel from '../components/admin/AdminTaskDelegationPanel'")
    expect(crew).toContain('<AdminTaskDelegationPanel initialProjectId={taskProjectId} />')
    expect(panel).toContain('<AdminWorkOrderAssignmentBoard')
    expect(panel).toContain('<AdminWorkOrderAssignmentForm')
    expect(panel).toContain("mode={editing ? 'edit' : 'create'}")
    expect(panel).not.toContain('window.location.reload')
  })

  it('uses exact owner-facing names and the same complete controls in create/edit', () => {
    expect(board).toContain('Assign Work Order')
    expect(form).toContain("'Assign Work Order' : 'Edit Work Order Assignment'")
    expect(form).toContain("'Assign' : 'Save Changes'")
    expect(form).toContain('Project')
    expect(form).toContain('Blueprint / Document')
    expect(form).toContain('Work Package')
    expect(form).toContain('SnapshotAssignmentPicker')
    expect(form).toContain('Assigned employees')
    expect(form).toContain('Due date')
    expect(form).toContain('Status')
    expect(form).toContain('Work Order Instructions')
    expect(`${panel}\n${board}\n${form}`).not.toMatch(/Assign work package/i)
  })

  it('renders Week by default, Month as a toggle, responsive day selection, filters, and Unscheduled', () => {
    expect(board).toContain("useState<AdminAssignmentCalendarView>('week')")
    expect(board).toContain("(['week', 'month'] as const)")
    expect(board).toContain('Previous')
    expect(board).toContain('Today')
    expect(board).toContain('Pending / Active')
    expect(board).toContain('Unscheduled')
    expect(board).toContain('grid-cols-7')
    expect(board).toContain('Week day selector')
    expect(board).toContain('MONTH_VISIBLE_LIMIT')
    expect(board).toContain('+{hidden} more')
  })

  it('shows required card/detail sources and retains the existing rating path', () => {
    expect(board).toContain('Assigned Hours:')
    expect(board).toContain('assignment.assigned_hours')
    expect(board).toContain('assignment.assigned_at')
    expect(board).toContain('assignment.scheduled_by_name')
    expect(board).toContain('assignment.completed_by_name')
    expect(board).toContain('assignment.completed_at')
    expect(board).toContain('assignment.hours_spent')
    expect(board).toContain('assignment.completion_notes')
    expect(panel).toContain('getQualityRatings')
    expect(panel).toContain('addQualityRating')
  })
})

describe('Work Order Instructions and immutable edit contract', () => {
  it('captures instructions independently and displays them after Crew Notes before Labor', () => {
    expect(service).toContain('workOrderInstructions')
    expect(service).toContain('normalizeWorkOrderInstructions')
    const scope = viewer.indexOf('<Section title="Scope">')
    const crewNotes = viewer.indexOf('<Section title="Crew Notes">')
    const instructions = viewer.indexOf('<Section title="Work Order Instructions">')
    const labor = viewer.indexOf('<Section title="Labor">')
    expect(scope).toBeGreaterThan(-1)
    expect(crewNotes).toBeGreaterThan(scope)
    expect(instructions).toBeGreaterThan(crewNotes)
    expect(labor).toBeGreaterThan(instructions)
    expect(viewer).toContain('payload.workOrderInstructions')
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.enforce_assignment_work_order_instructions')
    expect(migration).toContain("length(v_instructions) > 4000")
    expect(migration).toContain("BEFORE INSERT ON public.assignment_work_order_versions")
  })

  it('uses an authorized, locked, stale-safe, idempotent atomic reissue RPC', () => {
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.update_employee_task_assignment_with_work_order_and_snapshots')
    expect(migration).toContain('SECURITY DEFINER')
    expect(migration).toContain('SET search_path = public')
    expect(migration).toContain('v_uid := auth.uid()')
    expect(migration).toContain('NOT public.is_org_admin_for(v_org_id)')
    expect(migration).toContain('FOR UPDATE')
    expect(migration).toContain('last_admin_edit_request_id')
    expect(migration).toContain('Assignment changed; stale assignment edit')
    expect(migration).toContain('p_expected_work_order_version')
    expect(migration).toContain('p_expected_updated_at')
    expect(migration).toContain('idempotentReplay')
    expect(migration).toContain('REVOKE ALL ON FUNCTION public.update_employee_task_assignment_with_work_order_and_snapshots')
    expect(migration).toContain('GRANT EXECUTE ON FUNCTION public.update_employee_task_assignment_with_work_order_and_snapshots')
  })

  it('preserves historical versions and ordered max-15 snapshot attachments', () => {
    expect(migration).toContain('INSERT INTO public.assignment_work_order_versions')
    expect(migration).not.toContain('UPDATE public.assignment_work_order_versions')
    expect(migration).not.toContain('DELETE FROM public.assignment_work_order_versions')
    expect(migration).toContain('WITH ORDINALITY')
    expect(migration).toContain('ORDER BY submitted.ord')
    expect(migration).toContain('cardinality(v_snapshot_ids) > 15')
    expect(migration).toContain('Duplicate snapshot attachments are not allowed')
    expect(migration).toContain('Completed assignments cannot be edited')
    expect(migration096).toContain('display_order >= 0 AND display_order <= 14')
    expect(migration096).toContain('Maximum of 15 snapshots')
  })

  it('classifies operational-only edits without issuing an unnecessary version', () => {
    expect(migration).toContain('v_reissue :=')
    expect(migration).toContain('v_current_draft IS DISTINCT FROM v_incoming_draft')
    expect(migration).toContain('v_current_snapshot_ids IS DISTINCT FROM v_snapshot_ids')
    expect(migration).toContain('v_assignment.due_date IS DISTINCT FROM p_due_date')
    expect(migration).toContain('IF v_reissue THEN')
    expect(migration).toContain('v_next_version := v_current_version;')
    expect(service).toContain("rpc('update_employee_task_assignment_with_work_order_and_snapshots'")
  })
})
