import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const panelPath = join(process.cwd(), 'src/components/employee/EmployeeMyTasksPanel.tsx')
const viewerPath = join(process.cwd(), 'src/components/employee/EmployeeWorkOrderViewer.tsx')
const servicePath = join(process.cwd(), 'src/services/employeeTaskAssignmentService.ts')
const panel = readFileSync(panelPath, 'utf8')
const viewer = readFileSync(viewerPath, 'utf8')
const service = readFileSync(servicePath, 'utf8')

describe('Employee Work Order UI contract', () => {
  it('integrates View Work Order into the existing employee task panel without creating another portal page', () => {
    expect(panel).toContain('EmployeeWorkOrderViewer')
    expect(panel).toContain('View Work Order')
    expect(panel).toContain('setWorkOrderAssignmentId(task.id)')
    expect(panel).toContain('getMyEmployeeTasks')
    expect(panel).toContain('updateMyEmployeeTask')

    const employeeFiles = readdirSync(join(process.cwd(), 'src/components/employee'))
    expect(employeeFiles).toContain('EmployeeMyTasksPanel.tsx')
    expect(employeeFiles).toContain('EmployeeWorkOrderViewer.tsx')
    expect(employeeFiles.filter((name) => /WorkOrder.*Page|Portal.*WorkOrder/i.test(name))).toEqual([])
  })

  it('keeps existing completion and status behavior unchanged around the new action', () => {
    expect(panel).toContain('markInProgress')
    expect(panel).toContain('markComplete')
    expect(panel).toContain('saveNotes')
    expect(panel).toContain("status: 'in_progress'")
    expect(panel).toContain("status: 'completed'")
    expect(service).toContain('p_hours_spent')
    expect(panel).not.toContain('setDraftNotes({})')
    expect(panel).not.toContain('setDraftHours({})')
  })

  it('calls get_my_employee_work_order with assignment ID only and uses the immutable payload source', () => {
    expect(service).toContain("rpc('get_my_employee_work_order'")
    expect(service).toContain('p_assignment_id: cleanAssignmentId')
    const readStart = service.indexOf('export async function getMyEmployeeWorkOrder')
    const readBody = service.slice(readStart, service.indexOf('export async function updateMyEmployeeTask'))
    expect(readBody).not.toMatch(/orgId|employeeId|workPackageId|blueprintSetId|storage/i)
    expect(viewer).toContain('getMyEmployeeWorkOrder(assignmentId)')
    expect(viewer).toContain('parseWorkOrderPayload(workOrder)')
    expect(viewer).not.toContain('getBackupData')
    expect(viewer).not.toContain('getOperationsBlueprint')
  })

  it('renders the required Work Order sections from known payload fields only', () => {
    expect(viewer).toContain('WorkOrderHeader')
    expect(viewer).toContain('Scope')
    expect(viewer).toContain('Labor')
    expect(viewer).toContain('Items')
    expect(viewer).toContain('Electrical Symbols')
    expect(viewer).toContain('Wire Quantities')
    expect(viewer).toContain('Animation Route')
    expect(viewer).toContain('roughInHours')
    expect(viewer).toContain('trimHours')
    expect(viewer).toContain('testingHours')
    expect(viewer).toContain('cleanupHours')
    expect(viewer).toContain('totalHours')
    expect(viewer).toContain('payload.items')
    expect(viewer).toContain('payload.electricalSymbols')
    expect(viewer).toContain('payload.wireQuantities')
    expect(viewer).toContain('payload.animationRoute')
    expect(viewer).toContain('payload.animationPresentation')
    expect(viewer).not.toContain('Object.entries(payload)')
  })

  it('renders Crew Notes separately after Scope and reuses read-only animation playback', () => {
    const scopeIndex = viewer.indexOf('<Section title="Scope">')
    const crewNotesIndex = viewer.indexOf('<Section title="Crew Notes">')
    const laborIndex = viewer.indexOf('<Section title="Labor">')
    expect(scopeIndex).toBeGreaterThan(-1)
    expect(crewNotesIndex).toBeGreaterThan(scopeIndex)
    expect(laborIndex).toBeGreaterThan(crewNotesIndex)
    expect(viewer).toContain('whitespace-pre-wrap break-words')
    expect(viewer).toContain('PackageAnimationPlaybackControls')
    expect(viewer).toContain('Read-only playback')
    expect(viewer).toContain('onActivate={() => setActive(true)}')
    expect(viewer).toContain('onDeactivate={() => setActive(false)}')
    expect(viewer).not.toMatch(/PackageAnimationRouteBuilder|onDraftChange|onSave|route picking/i)
  })

  it('uses safe loading and unavailable states and prevents stale assignment responses', () => {
    expect(viewer).toContain('Loading Work Order')
    expect(viewer).toContain('No Work Order has been issued for this task yet.')
    expect(viewer).toContain('Work Order unavailable.')
    expect(viewer).toContain('requestSeq')
    expect(viewer).toContain('if (requestSeq.current !== seq) return')
    expect(viewer).toContain('setState({ loading: true, result: null')
    expect(viewer).toContain('setSnapshotUrls({})')
    expect(viewer).toContain('setImageFailures({})')
  })

  it('keeps snapshot URL lookup separate, temporary, ordered, and matched by snapshot ID', () => {
    expect(viewer).toContain("fetch(`${supabaseUrl}/functions/v1/getAssignmentSnapshotUrls`")
    expect(viewer).toContain('fetchAssignmentSnapshotUrls(')
    expect(viewer).toContain("? { assignment_id: cleanAssignmentId, snapshot_id: refreshSnapshotId }")
    expect(viewer).toContain(": { assignment_id: cleanAssignmentId }")
    expect(viewer).toContain("'x-client-info': 'poweron-hub-employee-work-order'")
    expect(viewer).not.toContain("supabase.functions.invoke('getAssignmentSnapshotUrls'")
    expect(viewer).toContain('normalizeSnapshotUrls(data)')
    expect(viewer).toContain('unwrapSnapshotUrlPayload(value)')
    expect(viewer).toContain('value.data')
    expect(viewer).toContain('entry.id ?? entry.snapshot_id ?? entry.snapshotId')
    expect(viewer).toContain('entry.signed_url ?? entry.signedUrl')
    expect(viewer).toContain('entry.expires_at ?? entry.expiresAt')
    expect(viewer).toContain('snapshotUrls[selectedSnapshotId]')
    expect(viewer).not.toContain('snapshots[index]')
    expect(viewer).toContain('displayOrder')
    expect(viewer).toContain('sort((a, b) => a.displayOrder - b.displayOrder)')
    expect(viewer).toContain('expiresAt')
    expect(viewer).not.toContain('localStorage')
    expect(viewer).not.toContain('sessionStorage')
  })

  it('requests getAssignmentSnapshotUrls from completed Work Order metadata with assignment_id only for the initial batch', () => {
    const invokeStart = viewer.indexOf('fetchAssignmentSnapshotUrls(')
    const invokeBlock = viewer.slice(invokeStart, viewer.indexOf(')', invokeStart + 'fetchAssignmentSnapshotUrls('.length) + 1)
    expect(invokeStart).toBeGreaterThan(-1)
    expect(viewer).toContain('/functions/v1/getAssignmentSnapshotUrls')
    expect(invokeBlock).toContain(': { assignment_id: cleanAssignmentId }')
    expect(invokeBlock).toContain('? { assignment_id: cleanAssignmentId, snapshot_id: refreshSnapshotId }')
    expect(invokeBlock).not.toContain('org')
    expect(invokeBlock).not.toContain('employee')
    expect(invokeBlock).not.toContain('storage')

    const initialRequest = viewer.slice(viewer.indexOf('const requestKey = `${cleanAssignmentId}:${snapshotIdsKey}`'))
    expect(initialRequest).toContain('if (initialSnapshotUrlRequestKeyRef.current === requestKey) return')
    expect(initialRequest).toContain('void loadSnapshotUrls()')
    expect(initialRequest.indexOf('void loadSnapshotUrls()')).toBeLessThan(initialRequest.indexOf('const selectedSnapshot ='))
  })

  it('avoids supabase-js platform headers that break the deployed CORS allow-list', () => {
    const helperStart = viewer.indexOf('async function fetchAssignmentSnapshotUrls')
    expect(helperStart).toBeGreaterThan(-1)
    const helper = viewer.slice(helperStart, viewer.indexOf('function normalizeSnapshotUrls'))
    expect(helper).toContain("Authorization: `Bearer ${accessToken}`")
    expect(helper).toContain('apikey: anonKey')
    expect(helper).toContain("'Content-Type': 'application/json'")
    expect(helper).toContain("'x-client-info': 'poweron-hub-employee-work-order'")
    expect(helper).not.toContain('x-supabase-client-platform')
    expect(helper).not.toContain('functions.invoke')
  })

  it('uses assignment id and stable snapshot metadata identity as the only automatic URL request trigger', () => {
    expect(viewer).toContain('const snapshotIdsKey = useMemo(() => snapshots.map((snapshot) => snapshot.snapshotId).join')
    expect(viewer).toContain('if (!cleanAssignmentId || !state.result?.available || snapshots.length === 0) return')
    expect(viewer).toContain('const requestKey = `${cleanAssignmentId}:${snapshotIdsKey}`')

    const effectStart = viewer.indexOf('const requestKey = `${cleanAssignmentId}:${snapshotIdsKey}`')
    const effectEnd = viewer.indexOf('const selectedSnapshot =', effectStart)
    const urlEffect = viewer.slice(effectStart, effectEnd)
    expect(urlEffect).toContain('void loadSnapshotUrls()')
    expect(urlEffect).not.toMatch(/selectedSnapshotId|snapshotUrls|imageFailures|selectedUrl|Preview|Thumbnail/)
  })

  it('prevents initial invocation loops while allowing single-snapshot retry requests', () => {
    expect(viewer).toContain('initialSnapshotUrlRequestKeyRef.current = null')
    expect(viewer).toContain('if (initialSnapshotUrlRequestKeyRef.current === requestKey) return')
    expect(viewer).toContain('initialSnapshotUrlRequestKeyRef.current = requestKey')
    expect(viewer).toContain('void loadSnapshotUrls(snapshotId)')
    expect(viewer).toContain('void loadSnapshotUrls(selectedSnapshotId)')

    const loadDepsStart = viewer.indexOf('}, [assignmentId])')
    expect(loadDepsStart).toBeGreaterThan(-1)
    expect(viewer).not.toContain('}, [assignmentId, snapshots]')
    expect(viewer).not.toContain('}, [assignmentId, snapshotUrls]')
    expect(viewer).not.toContain('}, [assignmentId, imageFailures]')
  })

  it('invalidates stale signed URL responses and exits loading after function errors', () => {
    expect(viewer).toContain('urlRequestSeq.current += 1')
    expect(viewer).toContain('if (urlRequestSeq.current !== seq) return')
    expect(viewer).toContain('setSnapshotUrlError(true)')
    expect(viewer).toContain('setSnapshotUrlLoading(false)')
    expect(viewer).toContain('if (!isRefresh) setSnapshotUrlRequestCompleted(true)')
    expect(viewer).toContain('unavailable={urlRequestCompleted && !snapshotUrls[snapshot.snapshotId]}')
  })

  it('reuses the shared preview viewport and retries image loading once before showing Retry', () => {
    expect(viewer).toContain('BlueprintSnapshotPreviewViewport')
    expect(viewer).toContain('imageFailures')
    expect(viewer).toContain('refreshingSnapshotIds')
    expect(viewer).toContain('SnapshotThumbnail')
    expect(viewer).toContain('onThumbnailError')
    expect(viewer).toContain('onThumbnailLoad')
    expect(viewer).toContain('if (snapshotUrlLoading || refreshingSnapshotIds[snapshotId]) return')
    expect(viewer).toContain('if (current === 0)')
    expect(viewer).toContain('setImageFailures((prev) => ({ ...prev, [snapshotId]: 1 }))')
    expect(viewer).toContain('void loadSnapshotUrls(snapshotId)')
    expect(viewer).toContain('selectedFailureCount >= 2')
    expect(viewer).toContain('Preview unavailable')
    expect(viewer).toContain('Retry')
    expect(viewer).toContain('resetKey={`${selectedSnapshot.snapshotId}-${selectedUrl.expiresAt || selectedUrl.url}`}')
  })

  it('does not render an empty image src and waits for a usable URL before default preview', () => {
    expect(viewer).toContain('const firstUsable = snapshotsRef.current.find((snapshot) => nextUrls[snapshot.snapshotId])')
    expect(viewer).toContain('return firstUsable?.snapshotId ?? current')
    expect(viewer).not.toContain('setSelectedSnapshotId(result.snapshots[0]?.snapshotId')
    expect(viewer).toContain('selectedUrl && !selectedUrlRefreshing && selectedFailureCount < 2')
    expect(viewer).toContain('loading || !urlItem?.url')
    expect(viewer).toContain('src={urlItem.url}')
    expect(viewer).toContain('(!selectedUrl || selectedUrlRefreshing) && selectedFailureCount < 2')
    expect(viewer).not.toContain('imageUrl={selectedUrl?.url}')
    expect(viewer).not.toContain('src=""')
  })

  it('exits thumbnail loading when a completed URL request has no usable URL', () => {
    expect(viewer).toContain('snapshotUrlRequestCompleted')
    expect(viewer).toContain('setSnapshotUrlRequestCompleted(false)')
    expect(viewer).toContain('setSnapshotUrlRequestCompleted(true)')
    expect(viewer).toContain('unavailable={urlRequestCompleted && !snapshotUrls[snapshot.snapshotId]}')
    expect(viewer).toContain('if (failureCount >= 2 || unavailable)')
    expect(viewer).toContain('const noUsableUrls = urlRequestCompleted && snapshots.length > 0 && Object.keys(snapshotUrls).length === 0')
    expect(viewer).toContain('(error || noUsableUrls || selectedUrlUnavailable) && !selectedUrl')
  })

  it('keeps each snapshot retry independent and clears temporary URL state on assignment changes', () => {
    expect(viewer).toContain('setSnapshotUrls({})')
    expect(viewer).toContain('setRefreshingSnapshotIds({})')
    expect(viewer).toContain('setImageFailures({})')
    expect(viewer).toContain('const { [refreshSnapshotId]: _omitted, ...remaining } = prev')
    expect(viewer).toContain('setSnapshotUrls((prev) => ({ ...prev, ...nextUrls }))')
    expect(viewer).toContain('setImageFailures((prev) => ({ ...prev, [snapshotId]: 0 }))')
    expect(viewer).toContain('snapshot_id: refreshSnapshotId')
  })

  it('does not expose mutation, capture, reorder, or management controls in the viewer', () => {
    expect(viewer).not.toMatch(/Delete|Remove|caption edit|reorder|Capture Area|Snapshot Library|management/i)
    expect(viewer).not.toMatch(/updateBlueprintSnapshot|deleteBlueprintSnapshot|saveBlueprintSnapshot|assignment_snapshots|blueprint_snapshots/)
    expect(viewer).not.toContain('.update(')
    expect(viewer).not.toContain('.delete(')
    expect(viewer).not.toContain('.insert(')
  })

  it('does not render or store forbidden owner/internal fields', () => {
    expect(viewer).not.toMatch(/lead_employee_id|assigned_employee_ids|assigned_by|client_request_id|org_id/)
    expect(viewer).not.toMatch(/customerProposalSummary|pricing|estimates|material prices|labor rates|costs|markup|margin/i)
    expect(viewer).not.toMatch(/raw annotations|BackupData|animation graph|scene graph|diagnostics/i)
    expect(viewer).not.toMatch(/storage_path|bucket name|public URL/i)
  })

  it('keeps responsive desktop, tablet, and phone-safe layout classes', () => {
    expect(viewer).toContain('sm:')
    expect(viewer).toContain('lg:grid-cols')
    expect(viewer).toContain('grid gap-4')
    expect(viewer).not.toContain('overflow-x-scroll')
  })

  it('does not modify migrations for the UI phase', () => {
    expect(existsSync(join(process.cwd(), 'supabase/migrations/095_employee_work_order_read.sql'))).toBe(true)
    expect(viewerPath.endsWith('EmployeeWorkOrderViewer.tsx')).toBe(true)
  })
})
