/**
 * PortalDataFirewall — Customer Portal Data Isolation Rules
 *
 * This module documents and enforces the non-negotiable data boundary
 * between the customer-facing portal and the internal PowerOn Hub
 * operations platform.
 *
 * ─────────────────────────────────────────────────────────────────────
 *  ARCHITECTURE OVERVIEW
 * ─────────────────────────────────────────────────────────────────────
 *
 *  Customer Portal                  PowerOn Hub Ops
 *  ───────────────                  ────────────────
 *  Public form submission           SPARK agent
 *  ↓                                ↑
 *  portal-submit.ts (Netlify fn)    agent_messages table
 *  ↓                     ──────────►  (sanitized: 5 fields only)
 *  portal_leads table
 *  (service role key, server-side only)
 *
 * ─────────────────────────────────────────────────────────────────────
 *  NON-NEGOTIABLE RULES (enforce at all layers)
 * ─────────────────────────────────────────────────────────────────────
 *
 * RULE 1 — WRITE ISOLATION
 *   Portal writes ONLY to the `portal_leads` table.
 *   Portal functions NEVER write to:
 *     - leads, serviceLogs, gcContacts, serviceLeads (operational tables)
 *     - app_state, user_preferences, or any ops sync table
 *     - Any agent state table (call_sessions, call_scripts, etc.)
 *
 * RULE 2 — SANITIZED AGENTBUS BOUNDARY
 *   The only data that crosses from portal → ops side is a sanitized
 *   agentBus message dispatched via the `agent_messages` table.
 *   That message contains EXACTLY these 5 fields — no more:
 *     { name, service_type, city, email, phone }
 *   Fields NEVER included in the cross-boundary message:
 *     - address (full street address stays portal-side only)
 *     - description (work description stays portal-side only)
 *     - photos_urls (media stays portal-side only)
 *     - sq_ft, monthly_bill, battery_interest (sensitive project data)
 *     - drawings_available (document availability stays portal-side)
 *
 * RULE 3 — NO PORTAL USER CAN QUERY OPERATIONAL TABLES
 *   - The portal has no Supabase client credentials.
 *   - All portal API calls go through server-side Netlify functions only.
 *   - Anon key is NEVER used in any portal function.
 *   - RLS (Row Level Security) on portal_leads must block anon reads.
 *
 * RULE 4 — SERVICE ROLE KEY IS SERVER-SIDE ONLY
 *   - SUPABASE_SERVICE_ROLE_KEY is stored as a Netlify environment variable.
 *   - It is NEVER exposed to the browser, NEVER in VITE_* vars, NEVER
 *     in any client-side bundle.
 *   - The portal-submit.ts function is the sole consumer of this key
 *     for portal_leads writes.
 *
 * RULE 5 — NO READ-BACK OF OPERATIONAL DATA
 *   - Portal functions do not read from operational tables to validate
 *     or enrich submissions.
 *   - Portal confirmation (portal-confirm-email.ts) works only from
 *     data passed to it at submission time; it does not query Supabase.
 *
 * ─────────────────────────────────────────────────────────────────────
 *  PORTAL_LEADS TABLE SCHEMA
 * ─────────────────────────────────────────────────────────────────────
 *
 *  Column               Type          Notes
 *  ───────────────────  ────────────  ─────────────────────────────────
 *  id                   uuid          PK, generated by portal-submit
 *  created_at           timestamptz   default now()
 *  confirmation_number  text          POL-XXXXXXXX format
 *  service_type         text          enum: electrical_service | panel_upgrade |
 *                                       solar_installation | battery_storage |
 *                                       ev_charger | whole_home_rewire |
 *                                       lighting | troubleshooting |
 *                                       commercial | other
 *  name                 text          customer full name
 *  email                text          customer email
 *  phone                text          customer phone
 *  address              text          street address (portal-side only)
 *  city                 text          city
 *  description          text          work description (portal-side only)
 *  urgency              text          emergency | urgent | standard | flexible
 *  photos_urls          text[]        uploaded photo URLs (portal-side only)
 *  sq_ft                numeric       optional, project square footage
 *  property_type        text          optional: residential | commercial | etc.
 *  roof_type            text          optional: shingle | tile | metal | flat | other
 *  utility              text          optional: utility company name
 *  monthly_bill         numeric       optional: average monthly electric bill
 *  battery_interest     boolean       interested in battery backup?
 *  drawings_available   boolean       drawings / plans available?
 *  status               text          new | contacted | quoted | closed
 *
 * ─────────────────────────────────────────────────────────────────────
 *  SUPABASE RLS POLICY REQUIREMENTS
 * ─────────────────────────────────────────────────────────────────────
 *
 *  portal_leads table must have:
 *    - RLS enabled
 *    - INSERT policy: service_role only (no anon insert)
 *    - SELECT policy: authenticated ops users only (staff/owner)
 *    - No policy permitting anon SELECT, UPDATE, or DELETE
 *
 *  Recommended SQL migration (add to supabase/migrations/):
 *
 *  ALTER TABLE portal_leads ENABLE ROW LEVEL SECURITY;
 *
 *  CREATE POLICY "portal_leads_insert_service_role"
 *    ON portal_leads FOR INSERT
 *    TO service_role WITH CHECK (true);
 *
 *  CREATE POLICY "portal_leads_select_authenticated"
 *    ON portal_leads FOR SELECT
 *    TO authenticated USING (true);
 *
 * ─────────────────────────────────────────────────────────────────────
 *  WHAT THE CROSS-BOUNDARY SPARK MESSAGE LOOKS LIKE
 * ─────────────────────────────────────────────────────────────────────
 *
 *  {
 *    "id": "<uuid>",
 *    "from": "PORTAL",
 *    "to": "SPARK",
 *    "type": "data_updated",
 *    "payload": {
 *      "event": "new_portal_lead",
 *      "confirmation_number": "POL-XXXXXXXX",
 *      "name": "<customer name>",
 *      "service_type": "<service_type>",
 *      "city": "<city>",
 *      "email": "<email>",
 *      "phone": "<phone>"
 *    },
 *    "timestamp": <epoch ms>,
 *    "status": "pending"
 *  }
 *
 * ─────────────────────────────────────────────────────────────────────
 *  ENVIRONMENT VARIABLES
 * ─────────────────────────────────────────────────────────────────────
 *
 *  Required in Netlify → Site settings → Environment variables:
 *
 *  SUPABASE_URL              — Supabase project URL (also used by app)
 *  SUPABASE_SERVICE_ROLE_KEY — Service role secret (portal functions only)
 *  RESEND_API_KEY            — Resend email API key (shared with sendEmail.ts)
 *  URL                       — Auto-set by Netlify (deploy URL for internal calls)
 *
 * ─────────────────────────────────────────────────────────────────────
 *  AUDIT CHECKLIST (verify before each portal release)
 * ─────────────────────────────────────────────────────────────────────
 *
 *  [ ] portal-submit.ts uses SUPABASE_SERVICE_ROLE_KEY (not anon key)
 *  [ ] portal-submit.ts writes ONLY to portal_leads
 *  [ ] SPARK message payload contains ONLY the 5 approved fields
 *  [ ] portal-confirm-email.ts does NOT query any Supabase table
 *  [ ] No VITE_SUPABASE_SERVICE_ROLE_KEY exists in any .env file
 *  [ ] portal_leads has RLS enabled with correct policies
 *  [ ] No operational table (leads, serviceLogs, etc.) is touched
 *  [ ] CustomerPortal UI calls only /.netlify/functions/portal-submit
 *  [ ] No direct Supabase client calls from CustomerPortal component
 */

// ── Type: Cross-boundary SPARK payload (enforced shape) ─────────────────────

/**
 * The ONLY data shape permitted to cross from portal → ops via agentBus.
 * This type is intentionally narrow.
 */
export interface PortalSparkPayload {
  event: 'new_portal_lead'
  confirmation_number: string
  /** Customer name — full name only, no address info */
  name: string
  /** Service category slug */
  service_type: string
  /** City — geographic context without full street address */
  city: string
  /** Contact email */
  email: string
  /** Contact phone */
  phone: string
}

// ── Type: portal_leads row shape ─────────────────────────────────────────────

export type PortalLeadStatus = 'new' | 'contacted' | 'quoted' | 'closed'

export type PortalServiceType =
  | 'electrical_service'
  | 'panel_upgrade'
  | 'solar_installation'
  | 'battery_storage'
  | 'ev_charger'
  | 'whole_home_rewire'
  | 'lighting'
  | 'troubleshooting'
  | 'commercial'
  | 'other'

export type PortalUrgency = 'emergency' | 'urgent' | 'standard' | 'flexible'

export interface PortalLead {
  id: string
  created_at?: string
  confirmation_number: string
  service_type: PortalServiceType
  name: string
  email: string
  phone: string
  address: string
  city: string
  description: string
  urgency: PortalUrgency
  photos_urls: string[]
  sq_ft?: number | null
  property_type?: string | null
  roof_type?: string | null
  utility?: string | null
  monthly_bill?: number | null
  battery_interest: boolean
  drawings_available: boolean
  status: PortalLeadStatus
}

// ── Constants: Firewall-approved field list ───────────────────────────────────

/**
 * The exact set of fields permitted in the cross-boundary SPARK message.
 * No other portal_lead fields may be included.
 */
export const SPARK_ALLOWED_FIELDS = [
  'name',
  'service_type',
  'city',
  'email',
  'phone',
] as const

export type SparkAllowedField = (typeof SPARK_ALLOWED_FIELDS)[number]

/**
 * Enforces the firewall by extracting only SPARK_ALLOWED_FIELDS from a lead.
 * Used by portal-submit.ts before constructing the agentBus message.
 *
 * @param lead - The full portal lead record
 * @returns Sanitized payload safe to cross the ops boundary
 */
export function buildSparkSanitizedPayload(
  lead: Pick<PortalLead, SparkAllowedField>,
  confirmationNumber: string
): PortalSparkPayload {
  return {
    event: 'new_portal_lead',
    confirmation_number: confirmationNumber,
    name: lead.name,
    service_type: lead.service_type,
    city: lead.city,
    email: lead.email,
    phone: lead.phone,
  }
}

/**
 * Validates that a given object contains only the SPARK-allowed fields
 * (no extra keys that could leak restricted portal data).
 *
 * @param payload - Object to validate
 * @returns true if the payload is safe, false if it contains disallowed keys
 */
export function validateSparkPayloadBoundary(
  payload: Record<string, unknown>
): boolean {
  const allowedKeys = new Set<string>([
    'event',
    'confirmation_number',
    ...SPARK_ALLOWED_FIELDS,
  ])

  for (const key of Object.keys(payload)) {
    if (!allowedKeys.has(key)) {
      console.error(
        `[PortalDataFirewall] BOUNDARY VIOLATION: disallowed key "${key}" in SPARK payload`
      )
      return false
    }
  }

  return true
}

// ── Runtime guard: Warn if anon key is used in portal context ────────────────

/**
 * Called defensively in any portal-adjacent code to confirm that
 * the anon key is NOT being used for portal_leads operations.
 *
 * This is a belt-and-suspenders check — the real enforcement is that
 * portal functions use SUPABASE_SERVICE_ROLE_KEY and never expose it.
 *
 * @param keyHint - First 8 characters of the key being used (for logging)
 * @param context - Description of where this is being called from
 */
export function assertNotAnonKey(keyHint: string, context: string): void {
  // Supabase anon keys always start with "eyJhbGc" (base64 JWT header)
  // Service role keys also start with "eyJhbGc" but are longer and used server-side only.
  // This guard is a documentation/logging checkpoint, not a cryptographic check.
  if (typeof keyHint === 'string' && keyHint.startsWith('VITE_')) {
    console.error(
      `[PortalDataFirewall] FIREWALL VIOLATION in ${context}: ` +
        `A VITE_ prefixed key was detected. Portal operations must use ` +
        `server-side service role key only. Anon key must NOT be used for portal_leads.`
    )
  }
}
