/**
 * ATB-6 Preview-only provider fleet. Never imported into Live mapping.
 * Labeled DEMO DATA wherever it is rendered.
 */
import type { ProviderCapabilityView } from '@/components/v15r/app-brain/control-tower/controlTowerTypes'

const NO_QUOTA = { executionTokens: true, quotaRemaining: false, quotaPercent: false, resetAt: false } as const
const LOCAL_USAGE = { executionTokens: false, quotaRemaining: false, quotaPercent: false, resetAt: false } as const

export const PREVIEW_FLEET_LABEL = 'DEMO DATA · Preview fleet'

export const PREVIEW_PROVIDER_FLEET: ProviderCapabilityView[] = [
  {
    providerId: 'claude',
    providerDisplayName: 'Claude Code',
    providerKind: 'provider',
    providerLogoKey: 'claude',
    installed: true,
    available: true,
    availabilitySource: 'runtime-probe',
    cliVersion: '2.1.277',
    workerCapable: true,
    supportedRoles: ['architect', 'implementer', 'verifier'],
    local: false,
    lastRefreshedAt: '2026-09-22T00:00:00.000Z',
    models: [
      {
        modelId: 'claude-sonnet-5',
        modelDisplayName: 'claude-sonnet-5',
        availability: 'configured-unverified',
        availabilitySource: 'configured-allowlist',
        effortLevels: ['low', 'medium', 'high', 'extra-high'],
        defaultEffort: 'high',
        reportedRuntimeModel: 'claude-sonnet-5',
        configuredModel: 'claude-sonnet-5',
        contextWindow: null,
        usageCapabilities: { ...NO_QUOTA },
      },
      {
        modelId: 'claude-opus-4-6',
        modelDisplayName: 'claude-opus-4-6',
        availability: 'available',
        availabilitySource: 'execution-evidence',
        effortLevels: ['low', 'medium', 'high', 'extra-high'],
        defaultEffort: 'high',
        reportedRuntimeModel: 'claude-opus-4-6',
        configuredModel: null,
        contextWindow: null,
        usageCapabilities: { ...NO_QUOTA },
      },
    ],
  },
  {
    providerId: 'codex',
    providerDisplayName: 'Codex',
    providerKind: 'provider',
    providerLogoKey: 'codex',
    installed: true,
    available: true,
    availabilitySource: 'runtime-probe',
    cliVersion: '0.153.4',
    workerCapable: true,
    supportedRoles: ['implementer', 'verifier'],
    local: false,
    lastRefreshedAt: '2026-09-22T00:00:00.000Z',
    models: [
      {
        modelId: 'gpt-5.6',
        modelDisplayName: 'gpt-5.6',
        availability: 'available',
        availabilitySource: 'provider-enumeration',
        effortLevels: ['low', 'medium', 'high', 'extra-high'],
        defaultEffort: 'medium',
        reportedRuntimeModel: null,
        configuredModel: 'gpt-5.6',
        contextWindow: null,
        usageCapabilities: { ...NO_QUOTA },
      },
      {
        modelId: 'gpt-5.6-sol',
        modelDisplayName: 'gpt-5.6-sol',
        availability: 'available',
        availabilitySource: 'provider-enumeration',
        effortLevels: ['low', 'medium', 'high', 'extra-high'],
        defaultEffort: 'high',
        reportedRuntimeModel: null,
        configuredModel: null,
        contextWindow: null,
        usageCapabilities: { ...NO_QUOTA },
      },
    ],
  },
  {
    providerId: 'ollama',
    providerDisplayName: 'Ollama',
    providerKind: 'provider',
    providerLogoKey: 'ollama',
    installed: true,
    available: true,
    availabilitySource: 'runtime-probe',
    cliVersion: '0.34.0',
    workerCapable: true,
    supportedRoles: ['implementer'],
    local: true,
    lastRefreshedAt: '2026-09-22T00:00:00.000Z',
    models: [
      {
        modelId: 'llama3.1:8b',
        modelDisplayName: 'llama3.1:8b',
        availability: 'available',
        availabilitySource: 'local-runtime',
        effortLevels: [],
        defaultEffort: null,
        reportedRuntimeModel: 'llama3.1:8b',
        configuredModel: 'llama3.1:8b',
        contextWindow: null,
        usageCapabilities: { ...LOCAL_USAGE },
      },
      {
        modelId: 'qwen2.5-coder:14b',
        modelDisplayName: 'qwen2.5-coder:14b',
        availability: 'available',
        availabilitySource: 'local-runtime',
        effortLevels: [],
        defaultEffort: null,
        reportedRuntimeModel: null,
        configuredModel: null,
        contextWindow: null,
        usageCapabilities: { ...LOCAL_USAGE },
      },
    ],
  },
  {
    providerId: 'cursor-editor',
    providerDisplayName: 'Cursor Editor',
    providerKind: 'diagnostic',
    providerLogoKey: 'cursor',
    installed: true,
    available: true,
    availabilitySource: 'configured',
    cliVersion: null,
    workerCapable: false,
    supportedRoles: [],
    local: true,
    lastRefreshedAt: '2026-09-22T00:00:00.000Z',
    models: [],
  },
  {
    providerId: 'cursor-agent',
    providerDisplayName: 'Cursor Agent',
    providerKind: 'provider',
    providerLogoKey: 'cursor',
    installed: false,
    available: false,
    availabilitySource: 'unavailable',
    cliVersion: null,
    workerCapable: false,
    supportedRoles: [],
    local: true,
    lastRefreshedAt: '2026-09-22T00:00:00.000Z',
    models: [],
  },
]

/** Preview-only demo token count. Live must never read this. */
export const PREVIEW_DEMO_TOKEN_USAGE: Record<string, number> = {
  claude: 12345,
  codex: 8420,
}
