/**
 * src/features/blueprint-vr/buildingModelDefaults.ts
 *
 * Deterministic fallback building models for the different blueprint suite
 * shapes the Generate VR experience can encounter.
 *
 * Implementation note (W3.7):
 * This module now delegates layout generation to the Blueprint plan scanner so
 * that the 2D plan, the 3D dollhouse, and the fallback always share the same
 * non-overlapping geometry. The scanner provides a long/narrow Beauty Salon
 * suite (18 ft × 50 ft), a commercial tenant suite, a residential layout, an
 * electrical-only room, and a generic fallback.
 *
 * The functions here remain backward-compatible: existing callers asking for a
 * `salon` / `commercial` / `electrical` / `residential` model still get a
 * complete BlueprintBuildingModel, only now it is generated through the
 * scanner contract and therefore stays consistent across views.
 */

import type { BlueprintBuildingModel } from './buildingModel'
import {
  buildAp01CalibratedSalonPlanScan,
  scanBlueprintPlan,
  convertPlanScanToBuildingModel,
} from './blueprintPlanScanner'

// ─────────────────────────────────────────────────────────────────────────────
// Layout Type Detection
// ─────────────────────────────────────────────────────────────────────────────

export type DefaultLayoutType =
  | 'residential'
  | 'commercial'
  | 'salon'
  | 'utility'
  | 'electrical'
  | 'generic'

/**
 * Detect likely layout type from blueprint metadata.
 */
export function detectLayoutType(
  title?: string,
  projectName?: string,
  discipline?: string,
): DefaultLayoutType {
  const combined = `${title || ''} ${projectName || ''} ${discipline || ''}`.toLowerCase()

  if (
    combined.includes('salon') ||
    combined.includes('spa') ||
    combined.includes('beauty') ||
    combined.includes('barber') ||
    combined.includes('nail') ||
    combined.includes('tenant')
  ) {
    return 'salon'
  }

  if (
    combined.includes('panel room') ||
    combined.includes('electrical room') ||
    combined.includes('mep')
  ) {
    return 'electrical'
  }

  if (
    combined.includes('office') ||
    combined.includes('commercial') ||
    combined.includes('suite') ||
    combined.includes('corporate')
  ) {
    return 'commercial'
  }

  if (
    combined.includes('residential') ||
    combined.includes('house') ||
    combined.includes('home') ||
    combined.includes('apartment')
  ) {
    return 'residential'
  }

  return 'generic'
}

// ─────────────────────────────────────────────────────────────────────────────
// Layout → scanner-context bridge
// ─────────────────────────────────────────────────────────────────────────────

type ScannerLayoutContext = Parameters<typeof scanBlueprintPlan>[0]

function layoutTypeToScannerHint(
  layoutType: DefaultLayoutType,
  title?: string,
  projectName?: string,
): ScannerLayoutContext {
  const seed: ScannerLayoutContext = {
    projectName,
    blueprintTitle: title,
  }
  switch (layoutType) {
    case 'salon':
      seed.projectName = projectName || 'Beauty Salon'
      seed.blueprintTitle = title || `${seed.projectName} Tenant Improvement`
      return seed
    case 'commercial':
      seed.projectName = projectName || 'Commercial Suite'
      seed.blueprintTitle = title || `${seed.projectName} Office Tenant`
      return seed
    case 'electrical':
    case 'utility':
      seed.projectName = projectName || 'Electrical Room'
      seed.blueprintTitle = title || `${seed.projectName} Panel Layout`
      return seed
    case 'residential':
      seed.projectName = projectName || 'Residential'
      seed.blueprintTitle = title || `${seed.projectName} Home Plan`
      return seed
    case 'generic':
    default:
      seed.projectName = projectName || 'Project'
      seed.blueprintTitle = title || `${seed.projectName} Generic Plan`
      return seed
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Create a default building model for the given layout type.
 *
 * The model is now generated by running the deterministic scanner with the
 * appropriate context so it stays in lock-step with the rest of the Generate
 * VR pipeline.
 */
export function createDefaultBuildingModel(
  layoutType: DefaultLayoutType = 'generic',
  title?: string,
  projectName?: string,
): BlueprintBuildingModel {
  const hint = layoutTypeToScannerHint(layoutType, title, projectName)
  const scan = scanBlueprintPlan(hint)
  const model = convertPlanScanToBuildingModel(scan)

  // Preserve project / title display so the dollhouse and plan viewers can use
  // them. createDefaultBuildingModel callers historically built their own
  // display labels, so we patch the model name to mirror the prior behaviour.
  if (title || projectName) {
    const layoutDisplay =
      layoutType === 'salon' ? 'Beauty Salon Suite' :
      layoutType === 'commercial' ? 'Commercial Suite' :
      layoutType === 'residential' ? 'Residential Layout' :
      layoutType === 'electrical' || layoutType === 'utility' ? 'Electrical Panel Room' :
      'Suite Layout'
    model.name = title ? `${title} (${layoutDisplay})` : layoutDisplay
    model.metadata.displayLabel = `${projectName || 'Project'} – ${layoutDisplay}`
  }
  return model
}

/**
 * Create a default model based on blueprint metadata, auto-detecting layout type.
 */
export function createAutoDetectedDefaultModel(
  title?: string,
  projectName?: string,
  discipline?: string,
): BlueprintBuildingModel {
  const layoutType = detectLayoutType(title, projectName, discipline)
  return createDefaultBuildingModel(layoutType, title, projectName)
}

/**
 * Deterministic AP-01 Beauty Salon calibrated plan used when direct PDF trace
 * is unavailable for the Proposed Dimensioned Plan sheet.
 */
export function createAp01CalibratedSalonBuildingModel(
  title?: string,
  projectName?: string,
): BlueprintBuildingModel {
  const scan = buildAp01CalibratedSalonPlanScan({
    projectName: projectName || 'Beauty Salon',
    blueprintTitle: title || 'AP-01 Proposed Dimensioned Plan',
    sheetIndex: [{ pageNumber: 1, sheetTitle: 'AP-01 Proposed Dimensioned Plan' }],
  })
  const model = convertPlanScanToBuildingModel(scan)
  model.name = title ? `${title} (AP-01 Calibrated)` : 'AP-01 Calibrated Beauty Salon Suite'
  model.metadata.displayLabel = `${projectName || 'Project'} – AP-01 Calibrated Suite`
  return model
}
